name: 'Setup Node'
description: 'Setup Node with Yarn and Turbo Cache'
inputs:
  turbo:
    description: 'Whether to use Turbo Cache'
    default: false
    required: false
  version:
    description: 'Node version'
    default: '20'
    required: false

env:
  TURBO_CACHE_DIR: ./.turbo

runs:
  using: 'composite'
  steps:
    - name: Use Node.js v${{ inputs.version }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: ${{ inputs.version }}
        registry-url: https://registry.yarnpkg.com/

    - name: Install Yarn
      shell: bash
      run: npm i -g yarn

    - name: Locate Yarn Cache
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Yarn Cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
        restore-keys: |
          yarn-cache-folder-

    - name: Turbo Cache
      if: ${{ inputs.turbo }}
      uses: actions/cache@v4
      with:
        path: |
          node_modules/.cache/turbo
          .turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-

    - name: Install Dependencies
      run: yarn --immutable
      shell: bash
