name: "Setup Node"
description: "Setup Node with Yarn and caching"
inputs:
  turbo:
    description: 'Whether to use Turbo Cache'
    default: false
    required: false

runs:
  using: "composite"
  steps: 
    - name: Use Node.js v16
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
      with:
        node-version: 16
        registry-url: https://registry.yarnpkg.com/
    - name: Locate Yarn Cache
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Yarn Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
        restore-keys: |
          yarn-cache-folder-
    - name: Turbo Cache
      if: ${{ inputs.turbo }}
      uses: actions/cache@v3
      with:
        path: |
            node_modules/.cache/turbo
            ./*/**/.turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-
    - name: Install Dependencies
      run: yarn --immutable
      shell: bash